= Code.Gate? とは

=====
Code.Gate? は大阪公立大学の学生が中心となって運営する、プログラミングサークルです。
=====

== 基本情報

Code.Gate?ではプログラミング未経験者から経験者まで、すべての人にとってのエンジニアになるためのゲートとなることを目指した団体です。

実際のプロダクト（サービス）の開発を通して、エンジニアとして必要なスキルを身に着けていきます。

=== 触れる主な技術

* Frontend
** TypeScript
** React
* Backend
** Ruby on Rails
** Node.js
* Native App
** Flutter

== 大切にしたいこと（カルチャー）

=== 自律する

ただこなすなら誰でもできます。こなすエンジニアではなく、自身で考え動くことのできるエンジニアであり続けることを大切にしています。

自律をキーワードに、意思決定のできるエンジニアであり続けましょう。

=== 責任を持つ

責任範囲が個人で終わるのであれば何をしても自由です。ただそこに他者が入ってきた以上、任されたことに責任を持つべきであり、投げやりにしてはいけない。

自身が持った責任を無碍に扱うのではなく、その責任を背負い行動し続けることを大切にします。

=== コントローラーを持つ

身体や精神を壊しては元も子もない。負荷をかけるところはかけつつ、休むところはしっかり休む。長期的に継続していけるよう、自身のことを理解し、自分を操るコントローラーを持つ意識を持ち、着実に成長していくことを大切にします。

=== オープンである

誰であっても敬意を持って接すること。自分より能力が低いなどで上下関係を決して作らず、誰もが対等に扱われることを第一とする。仮に破った場合、最悪サークルから除外する可能性がある。

== 活動内容

=====
🎫 *New Joiner Quest*

参加した方が最初に行うことです！内容は以下のドキュメントに記載されています（早くて1, 2ヶ月、遅くとも3ヶ月で終了する予定です）

xref:quest:index.adoc[New Joiner Quest]
=====

=====
🖥️ **プロダクト（サービス）開発**

4ヶ月間集中してチームでプロダクトを開発していきます。手順は以下の通りです。

1. アイデア決め
2. 仕様書作成
3. 開発
4. 発表（Release）
=====