name: Publish to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - antora
    paths:
      - '**'
      - '.gitmodules'
  pull_request:
    types: [closed]
    branches:
      - antora
    paths:
      - '**'
      - '.gitmodules'

concurrency:
  group: github-pages
  cancel-in-progress: false
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.2
      with:
        ref: antora
        submodules: recursive
    - name: Configure Pages
      uses: actions/configure-pages@v5
      with:
        enablement: true
    - name: Install Node.js
      uses: actions/setup-node@v4.4.0
      with:
        node-version: '22'
    - name: Update submodules
      id: update
      run: git submodule update --init --remote --recursive 
    - name: Directory check
      run: |
        ls -la
    - name: Build UI
      run: |
        cd _ui
        npm ci
        npm i -g gulp
        gulp bundle
        cd ..
    - name: Install Antora
      run: npm i antora
    - name: check directory
      run: ls
    - name: Generate Site
      run: npx antora path.yml
    - name: Upload Artifacts
      uses: actions/upload-pages-artifact@v3
      with:
        path: build/site
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
